/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author Achicopalado
 */
public class Grafica extends javax.swing.JFrame {

    /**
     * Creates new form Grafica
     */
    public Grafica() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    boolean bandera = false; 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        produ3 = new javax.swing.JTextField();
        Button1 = new javax.swing.JButton();
        produ4 = new javax.swing.JTextField();
        produ2 = new javax.swing.JTextField();
        produ1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(produ3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 60, -1));

        Button1.setText("Grafica");
        Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button1ActionPerformed(evt);
            }
        });
        jPanel1.add(Button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, -1, -1));
        jPanel1.add(produ4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 60, -1));
        jPanel1.add(produ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 60, -1));
        jPanel1.add(produ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 60, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button1ActionPerformed
        bandera = true;
        repaint();
    }//GEN-LAST:event_Button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Grafica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField produ1;
    private javax.swing.JTextField produ2;
    private javax.swing.JTextField produ3;
    private javax.swing.JTextField produ4;
    // End of variables declaration//GEN-END:variables

    @Override
    public void paint(Graphics g){
        super.paint(g);
        if(bandera == true){
            
            //Placeholders para los datos de las graficas
            //Lo dejo aca para ternerlo listo y luego solo arreglar para la datos
            
            String pro1 = produ1.getText();
            String pro2 = produ2.getText();
            String pro3 = produ3.getText();
            String pro4 = produ4.getText();
            
            int proint1 = Integer.parseInt(pro1);
            int proint2 = Integer.parseInt(pro2);
            int proint3 = Integer.parseInt(pro3);
            int proint4 = Integer.parseInt(pro4);
            
            int total = proint1 + proint2 + proint3 + proint4; 
           
            int grade1 = proint1 * 360 / total;
            int grade2 = proint2 * 360 / total;
            int grade3 = proint3 * 360 / total;
            int grade4 = proint4 * 360 / total;
            
            g.setColor(new Color(255, 0, 0));
            //g.fillArc(x, y, WIDTH, HEIGHT, startAngle, arcAngle);
            g.fillArc(25, 80, 200, 200, 0, grade1);
            g.fillRect(250, 120, 20, 20);
            g.drawString("Gastos productora: " + pro1, 275, 135);
            
            g.setColor(new Color(0, 0, 255));
            //g.fillArc(x, y, WIDTH, HEIGHT, startAngle, arcAngle);
            g.fillArc(25, 80, 200, 200, grade1, grade2);
            g.fillRect(250, 150, 20, 20);
            g.drawString("Gastos ensambladora: " + pro2, 275, 165);
            
            g.setColor(new Color(0, 125, 0));
            //g.fillArc(x, y, WIDTH, HEIGHT, startAngle, arcAngle);
            g.fillArc(25, 80, 200, 200, grade1 + grade2, grade3);
            g.fillRect(250, 180, 20, 20);
            g.drawString("Gastos jefe: " + pro3, 275, 195);
           
            g.setColor(new Color(100, 100, 100));
            //g.fillArc(x, y, WIDTH, HEIGHT, startAngle, arcAngle);
            g.fillArc(25, 80, 200, 200, grade1 + grade2 + grade3, grade4);
            g.fillRect(250, 210, 20, 20);
            g.drawString("Gastos gerente: " + pro4, 275, 225);
        }
    }
}
